language: objective-c
osx_image: xcode9

before_install:
  - brew update
  - gem install xcpretty
  - gem install cocoapods --version 1.5.0
  - pod _1.5.0_ repo update

install:
  - pod _1.5.0_ install

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace KataTODOAPIClient.xcworkspace -scheme 'KataTODOAPIClient' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
