language: objective-c
osx_image: xcode7.2
cache: cocoapods

before_install:
  - brew update
  - brew install swiftlint
  - gem install xcpretty

script:
  - swiftlint
  - set -o pipefail && xcodebuild -workspace KataTODOAPIClient.xcworkspace -scheme 'KataTODOAPIClient' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c